name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.7'
        cache: 'npm'

    # Installation des dépendances Backend avec npm install
    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Run backend tests
      run: |
        cd backend
        npx jest --passWithNoTests

    # Installation des dépendances Frontend avec npm install
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Run frontend tests
      run: |
        cd frontend
        npm test -- --watchAll=false

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Build Docker image
      run: docker build -t gestion-etablissement:latest .

    - name: Deploy to Dev
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      run: echo "Deployment to Dev environment successful"
