name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install backend dependencies
      run: |
        if [ -d "backend" ]; then
          cd backend
          npm ci
        else
          echo "\u26A0\uFE0F Le dossier backend est introuvable"
          exit 1
        fi
      
    - name: Run backend tests
      run: |
        cd backend
        npm test || { echo "\u274C Tests backend échoués"; exit 1; }
    
    - name: Install frontend dependencies
      run: |
        if [ -d "frontend" ]; then
          cd frontend
          npm ci
        else
          echo "\u26A0\uFE0F Le dossier frontend est introuvable"
          exit 1
        fi
      
    - name: Run frontend tests
      run: |
        cd frontend
        npm test || { echo "\u274C Tests frontend échoués"; exit 1; }
      
    - name: Build frontend
      run: |
        cd frontend
        npm run build || { echo "\u274C Build échoué"; exit 1; }
      
    - name: Build Docker image
      run: |
        if command -v docker &> /dev/null; then
          echo "\u2705 Docker est installé"
          echo "Construction de l'image Docker..."
          docker build -t gestion-etablissement:latest .
        else
          echo "\u26A0\uFE0F Docker n'est pas installé ou pas accessible"
          exit 1
        fi
      
    - name: Deploy to Dev
      run: |
        echo "\u2705 Deployment to Dev environment successful"

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Production
      run: |
        echo "\u2705 Deployment to Production environment successful"
